# Default values for gitlab-tmax.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  timezone: Asia/Seoul
  registry:
    is_offline: false
    private_registry: 172.22.6.2:5000
  # logLevel: INFO #DEBUG, INFO, WARN, ERROR, FATAL, UNKNOWN

externalURL: http://gitlab.testdomain.com
tls:
  enabled: true

pvc:
  storageClassName: ""
  storage: 30Gi
  
ingress:
  hosts:
    domain: testdomain.com
    subdomain: gitlab

keycloak:
  enabled: false
  namespace: keycloak
  url: http://keycloak.testdomain.com
  secret: selfsigned-crt-secret
  client: gitlab
  client_secret: tmax_client_secret
image:
  kube:
    repo: docker.io/bitnami/kubectl
    tag: 1.32.4

  gitlab:
    repo: docker.io/gitlab/gitlab-ce
    tag: 18.0.2-ce.0
